In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [3]:
my_df = pd.DataFrame({"A" : [1,4,7,10,13],
                     "B" : [3,6,9,np.nan,15],
                     "C" : [2,5,np.nan,11,np.nan]})

In [4]:
imputer = SimpleImputer()

In [6]:
imputer.fit(my_df)
imputer.transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [7]:
my_df1 = imputer.fit_transform(my_df)

In [8]:
imputer.fit_transform(my_df)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [10]:
my_df2 = pd.DataFrame(imputer.fit_transform(my_df), columns = my_df.columns)

In [15]:
imputer.fit_transform(my_df[["B"]])

array([[ 3.  ],
       [ 6.  ],
       [ 9.  ],
       [ 8.25],
       [15.  ]])

In [16]:
my_df["B"] = imputer.fit_transform(my_df[["B"]])